### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by mzorn-58** [cdcepi/FluSight-forecast-hub#227]
Link for [the model output guidelines in our documentation](https://hubdocs.readthedocs.io/en/latest/format/model-output.html). should be https://hubdocs.readthedocs.io/en/latest/user-guide/model-output.html

**Comment by rborchering** [comment]
Thanks for pointing this out! Apologies for not noticing sooner, but I've updated the link now. Thanks again. Rebecca
